### ISSUE TITLE
Tabling declaration for DCG non-terminals

### ISSUE THREAD

**Issue by triska** [aarroyoc/advent-of-code-2020#3]
A small thing I noticed: To table a DCG non-terminal, use the non-terminal indicator `F//N` (note the `//`), for example:

<pre>
:- table expr//1.
</pre>

This is because there is no guarantee how or even whether a DCG non-terminal is compiled to a Prolog predicate.

**Comment by aarroyoc** [comment]
Thanks! I've always thought it always got transpiled to arguments arity + 2. I've updated the code
